config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boardcategories, only: [:index, :show]

  resources :boardposts
  resources :calendars
  resources :tags, only: [:new, :create] do
    resources :post_tags, only: [:new, :create]
  end

  resources :locations, except: [:update, :edit, :destroy]

  resources :searches, only: [:index]
  get 'searches/advanced', to: 'searches#advanced'
  get 'searches/advanced_form', to: 'searches#advanced_form'
  delete "/users/:id/connections" => "connections#delete", as: "delete_connection"
  delete "/boardcategories" => "boardposts#delete", as: "delete_post"
  get 'users/feed', to: 'users#feed'

  resources :useraudiofiles
  resources :conversations
  resources :users do
    resources :user_conversations, shallow: true
    resources :connections, shallow: true
  end



# post "/users/:user_id/connections" => "connections#create", :as => :create_connection
  root to: "pages#home"

  mount ActionCable.server => '/cable'
end

app/models/boardcategory.rb
class Boardcategory < ApplicationRecord
  has_many :boardposts

  validates :name, presence: true

  paginates_per 15
end

app/controllers/boardcategories_controller.rb
class BoardcategoriesController < ApplicationController
  def index
    @categories = Boardcategory.order(:name).page params[:page]
  end

  def show
    @category = Boardcategory.find(params[:id])
    @posts = @category.boardposts.page params[:page]
  end
end

app/views/boardcategories/index.html.erb
<br>
<div class="center-align">
  <div class="container">
    <div class="row">
      <div class="col s12 l12">
        <div class="card">
          <form action="/searches" method="get">
            <div class="input-field">
              <input id="search" type="search" name="keyword" required>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
        </div>
              <input type="submit" value="Search" class="btn valign"><br>
          </form>
      </div>
    </div>
  </div>
</div>
<div class="center-align">
  <br>

<a class="waves-effect waves-light btn-small" href="#modal1">Advanced Search</a>
<div id="modal1" class="modal">
  <div class="modal-content">
  <%=render "/searches/advanced_form"%>
  </div>
</div>
</div>


<div class="container">
  <h2 class="cyan-text text-darken-3"><strong>Categories</strong></h2>
  <br>
  <div class="collection">
    <% @categories.each do |category|%>
    <%= link_to "#{category.name}", boardcategory_path(category), :class => "collection-item cyan-text text-darken-3 center-align grey lighten-3", id: category.id %>
    <% end  %>
  </div>
</div>
<div class="container">
  <div class="center-align">
<%= link_to "Create Post", new_boardpost_path, :class => "waves-effect waves-light btn valign"%>
    <%= paginate @categories %>
  </div>
</div>
<br>

app/views/boardcategories/show.html.erb
<div class="container">
  <h2 class="cyan-text text-darken-3"><strong>Postings for <%= @category.name.capitalize %></strong></h2>
</div>
<br>
<div class="container">
  <div class="collection">
    <% @posts.each do |post| %>
    <%= link_to "#{post.title}", boardpost_path(post), :class => "collection-item cyan-text text-darken-3 center-align grey lighten-3" %>
    <% end %>
    <% if @posts.any? %>
    <%= paginate @posts %>
    <% end %>
  </div>
</div>
<div class="center-align">
  <!-- add auth -->
  <%= link_to "Create Post", new_boardpost_path, :class => "waves-effect waves-light btn valign", id: @category.id%>

</div>
  <%= link_to "Back to Categories", boardcategories_path %>