config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boardcategories, only: [:index, :show]

  resources :boardposts
  resources :calendars
  resources :tags, only: [:new, :create] do
    resources :post_tags, only: [:new, :create]
  end

  resources :locations, except: [:update, :edit, :destroy]

  resources :searches, only: [:index]
  get 'searches/advanced', to: 'searches#advanced'
  get 'searches/advanced_form', to: 'searches#advanced_form'
  delete "/users/:id/connections" => "connections#delete", as: "delete_connection"
  delete "/boardcategories" => "boardposts#delete", as: "delete_post"
  get 'users/feed', to: 'users#feed'

  resources :useraudiofiles
  resources :conversations
  resources :users do
    resources :user_conversations, shallow: true
    resources :connections, shallow: true
  end



# post "/users/:user_id/connections" => "connections#create", :as => :create_connection
  root to: "pages#home"

  mount ActionCable.server => '/cable'
end

app/models/boardpost.rb
class Boardpost < ApplicationRecord
  belongs_to :user
  belongs_to :boardcategory
  has_many :post_tags
  has_many :tags, through: :post_tags

  has_attached_file :image, styles: { large: "600x600", medium: "300x300", thumb: "150x150" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, :content, presence: true

  paginates_per 25

  def find_location
    locations = Location.order(created_at: :desc)
    locations.find_by(user_id: self.user_id)
  end
end

app/controllers/boardposts_controller.rb
class BoardpostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :find_post, only: [:show, :edit, :destroy, :update]
  before_action :find_cat_through_post, except: [:new, :create]

  def show
    @author = User.find(@post.user_id)
  end

  def new
    @post = Boardpost.new
    if !user_signed_in?
      redirect_to new_user_session_path
    end

  end

  def create
    @category = Boardcategory.find_by(name: params[:boardcategory][:name])
    puts @category
    puts params[:boardcategory][:name]
    @post = Boardpost.new(post_params)
    @post.user_id = current_user.id
    @post.boardcategory_id = @category.id
    if @post.save
      redirect_to boardpost_path(@post)
    else
      @errors = @post.errors.full_messages
      render :new
    end
  end

  def edit
    redirect_to '/' if current_user.id != @post.user_id
    # throw error?
  end

  def update
    @post.update_attributes(post_params)
    redirect_to boardpost_path(@post)
  end

  def destroy
    if current_user.id == @post.user_id
      @post.destroy
    end
    redirect_to '/boardcategories'
    # make it go to a success page?
  end

  private
    def post_params
      params.require(:boardpost).permit(:title, :content)
    end

    def find_post
      @post = Boardpost.find(params[:id])
    end


    def find_cat_through_post
      @category = Boardcategory.find(@post.boardcategory_id)
    end
end

app/views/boardposts/edit.html.erb
<div class="container">
  <h2 class="cyan-text text-darken-3">Edit This Posting</h2>
</div>


<%= form_for @post, html: {multipart:true} do |f|%>
  <%= f.label :title %>
  <%= f.text_area :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <div id="tag-form">
  </div>
  <%= link_to 'Add Tag', new_tag_path, :class => "addTag"%> <br>
  <%= f.file_field :image %>
  <%= submit_tag "Submit" %>
<%  end %>

app/views/boardposts/index.html.erb
<div class="container">
  <h2 class="cyan-text text-darken-3"><strong>Postings</strong></h2>
</div>
<br>
<div class="container">
  <div class="collection">
    <% @posts.each do |post| %>
    <%= link_to "#{post.title}", boardcategory_boardpost_path(@category, post), :class => "collection-item cyan-text text-darken-3 center-align grey lighten-3" %>
    <% end %>
    <% if @posts.any? %>
    <%= paginate @posts %>
    <% end %>
  </div>
</div>
<div class="center-align">
  <!-- add auth -->
  <%= link_to "Create Post", new_boardcategory_boardpost_path(@category), :class => "waves-effect waves-light btn valign"%>

</div>
  <%= link_to "Back to Categories", boardcategories_path %>

app/views/boardposts/new.html.erb
<div class="container">
  <h2 class="cyan-text text-darken-3">Create A New Posting</h2>
</div>

<% if @errors %>
  <% @errors.each do |message| %>
    <%= message %> <br>
  <% end %>
<% end %>

<div class="container cyan-text text-darken-3">
  <div class="row">
    <div class="col s12 l10">
<%= form_for @post do |f|%>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="input-field">
  <select name="boardcategory[name]">
    <option value="Band Looking for Players">Band Looking for Players</option>
    <option value="Bands Needed">Bands Needed</option>
    <option value="For Sale">For Sale</option>
    <option value="Players Looking for Bands">Players Looking for Bands</option>
    <option value="Players Looking to Jam">Players Looking to Jam</option>
    <option value="Music Services">Music Services</option>
    <option value="Paid Gigs">Paid Gigs</option>
  </select>
  <label>Category</label>
</div>

<div class="field">
  <%= f.label :content %>
  <%= f.text_area :content %>
</div>
<br>

  <div id="tags">
    <%= link_to 'Add a Tag', new_tag_path %>
  </div>
<br>

<div class="center-align">
  <%= submit_tag "Submit", :class => "waves-effect waves-light btn", :id => "submitPost" %>
<%  end %>
    </div>
  </div>
</div>
</div>

app/views/boardposts/show.html.erb
<div class="container">
  <h2 class="cyan-text text-darken-3"><strong><%= @post.title %></strong></h2>
  <div class="row">
    <div class="col s4">
      <div class="chip">
        <%= image_tag "#{@author.avatar}", :alt => "Contact Person" %>
        <%= link_to "#{@author.full_name}", user_path(@author) %>
      </div>
      <% if @author == current_user %>
        <%= link_to 'Edit Post', edit_boardpost_path(@post) %> | <%= button_to "Delete Post", boardpost_path(@post), method: 'delete', :class => "waves-effect"  %>


      <% end %>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col s12 l10">
      <div class="card-panel grey lighten-2 z-depth-3">
        <span class="flow-text center-align"><%= @post.content %>
        </span>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="chip">
    <%= link_to "#{@category.name}", boardcategory_path(@category)%>


    <i class="close material-icons">close</i>
  </div>
</div>