config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boardcategories, only: [:index, :show]

  resources :boardposts
  resources :calendars
  resources :tags, only: [:new, :create] do
    resources :post_tags, only: [:new, :create]
  end

  resources :locations, except: [:update, :edit, :destroy]

  resources :searches, only: [:index]
  get 'searches/advanced', to: 'searches#advanced'
  get 'searches/advanced_form', to: 'searches#advanced_form'
  delete "/users/:id/connections" => "connections#delete", as: "delete_connection"
  delete "/boardcategories" => "boardposts#delete", as: "delete_post"
  get 'users/feed', to: 'users#feed'

  resources :useraudiofiles
  resources :conversations
  resources :users do
    resources :user_conversations, shallow: true
    resources :connections, shallow: true
  end



# post "/users/:user_id/connections" => "connections#create", :as => :create_connection
  root to: "pages#home"

  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar,

                    styles: { large: "600x600>", medium: "300x300>", small: "100x100>", thumb: "150x150#" },
                    url: "/assets/:style/:attachment/:filename.:extension"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :user_conversations
  has_many :conversations, through: :user_conversations
  has_many :messages
  has_many :connections
  has_many :connected_users, through: :connections
  has_many :useraudiofiles
  has_many :boardposts
  has_many :dragonflymedia
  has_many :locations

  # validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  def all_feeds
    @feed = []
    bp = self.create_boardpost_feed
    cf = self.create_connects_feed
    au = self.create_audio_upload_feed
    au.each {|a| @feed << a}
    cf.each {|c| @feed << c}
    bp.each {|p| @feed << p}
    @feed.flatten!
    @feed.sort! {|b, a| a.created_at <=> b.created_at}
    return @feed
  end

  def create_boardpost_feed
    bp = []
    c_ids = []
    connects = self.connections
    connects.each {|conns| c_ids << conns.connected_user_id}
    c_ids.each  {|id| bp << Boardpost.where(user_id: id)}
    bp.flatten!
    bp.sort!{|b, a| a.created_at <=> b.created_at}

  end

  def create_connects_feed
    c = []
    c_ids = []
    connects = self.connections
    connects.each {|conns| c_ids << conns.connected_user_id}
    c_ids.each  {|id| c << Connection.where(user_id: id)}
    c.flatten!
    c.sort!{|b, a| a.created_at <=> b.created_at}

  end

  def create_audio_upload_feed
    af = []
    c_ids = []
    connects = self.connections
    connects.each {|conns| c_ids << conns.connected_user_id}
    c_ids.each  {|id| af << Useraudiofile.where(user_id: id)}
    af.flatten!
    af.sort!{|b, a| a.created_at <=> b.created_at}
  end

  def self.user_feed_audio_file
    my_users = self.connected_users

    my_users.each do |user|
      Useraudiofile.find_by(user_id: user.id)
      # user.connected_users
      # Boardpost.find_by(user_id: user.id)
    end
  end

  def full_name
    if first_name != nil && last_name != nil
    first_name + " " + last_name
    else
      username
    end
  end

  def find_location
    locations = Location.order(created_at: :desc)
    locations.find_by(user_id: self.id)
  end

  def self.create_with_omniauth(auth)

    user = find_or_create_by(uid: auth['uid'], provider:  auth['provider'])
    user.email = "#{auth['uid']}@#{auth['provider']}.com"
    user.password = auth['uid']
    user.name = auth['info']['name']
    if User.exists?(user)
      user
    else
      user.save!
      user
    end
  end

  def unread_messages
    unreads = []
    self.user_conversations.each do |uc|
      uc.unread_messages.each do |message|
        unreads << message
      end
    end
    return unreads
  end

  def find_convo(user)
    self.conversations.each do |convo|
      if convo.other_user(self) == user
        return convo
      end
    end
    nil
  end

  def has_convo?(user)
    self.conversations.each do |convo|
      if convo.other_user(self) == user
        return true
      end
    end
    false
  end

  def possible_connections
    @CU = self.connected_users
    @CUC = []
    @CU.each do |user|
      @CUC << user.connected_users
    end
    @CUC.flatten!
    @CUC = @CUC.select {|user| user != self || !@CU.include?(user)}
    @CUC.shuffle!
    @top_CUC = @CUC[0..4]
    @top_CUC.uniq!
    # i = 5
    # until(@top_CUC.length == 5 || @top_CUC == @CUC.uniq) do
    #   @top_CUC << @CUC[i]
    #   @top_CUC.uniq!
    #   i += 1
    # end
    return @top_CUC
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    # render 'users/show'
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    # redirect '/'
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    if current_user
      @locations = Location.near([current_user.latitude, current_user.longitude], 10)
    end
    @users = User.all
  end

  def feed
    if !user_signed_in?
      redirect_to redirect_to new_user_session_path
    end
    @user = current_user
    @feed = @user.all_feeds
    @posts = Boardpost.all
    @categories = Boardcategory.all
    @users = User.all
   end

  def show
    @user = User.find(params[:id])
    @connections = @user.connections
    # @locations = Location.where(user_id: params[:id])
    # @current_user = User.find(current_user.id)
    # @locations = Location.where(user_id: current_user.id)
    # @location = @locations.last
    @conversations = @user.conversations
    @conversations = @conversations.sort_by{|convo| UserConversation.find_by(user_id: @user.id, conversation_id: convo.id).unread_messages }
    @conversations = @conversations[0..5]
  end

  def edit
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
      if @user.update(password_params)
        bypass_sign_in(@user)
        redirect_to root_path
      else
        render "edit"
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      bypass_sign_in(@user)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
  end
  def update_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :bio, :location, :band_status, :experience, :instruments, :slogan, :avatar, :audio_file_content_type)
  end
  def update_user_audio_files_params
    params.require(:audio).permit(:file)
  end
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<div class="container">
  <h2 class="cyan-text text-darken-3">Edit <%= @user.username %></h2>
</div>


<div class="container cyan-text text-darken-3">
  <div class="row">
    <div class="col s12 l10">
      <%= form_for(@user, as: @user, url: "/users/#{@user.id}", html: { multipart: true, method: :patch }) do |f| %>


      <div class="field">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :location %><br />
        <%= f.text_field :location %>
      </div>

      <div class="field">
        <%= f.label :band_status %>
        <%= f.text_field :band_status %>
      </div>

      <div class="input-field">
        <select name="user[experience]">
          <option value="" disabled selected><%=@user.experience%></option>
          <option value="Just started playing">Just started playing</option>
          <option value="I play with friends a bit">I play with friends a bit</option>
          <option value="Playing local gigs">Playing local gigs</option>
          <option value="Music Is My Job and Life">Music Is My Job And Life</option>
        </select>
        <label>Experience levels:</label>
      </div>

      <div class="field">
        <%= f.label :instruments %><br />
        <%= f.text_field :instruments %>
      </div>

      <div class="field">
        <%= f.label :bio %><br />
        <%= f.text_area :bio, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :slogan %><br />
        <%= f.text_field :slogan, autocomplete: "off" %>
      </div>
        <div class="field">
          <%= f.label :avatar %><br />
          <%= f.file_field :avatar %>
        </div>
      <div class="center-align">
        <div class="actions">
          <%= f.submit "Update", :class => "waves-effect waves-light btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
<br>

<div class="cancel">
<div class="container">
  <h2 class="cyan-text text-darken-3">YOU BE 9ing IF YOU Cancel My Account</h2>
</div>

<div class="container">
<p>Unhappy? <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>
</div>
</div>

<button id="cancelaccount" class="white"></button>

app/views/users/feed.html.erb
<div class="feedwrapper">
  <div class="row">
    <div class="col s4">
      <div class="card cyan darken-3 center-align">
        <span class="card-title title grey-text text-lighten-2"><strong>News Feed</span>
  <% @feed.each do |f| %>
    <% if f.class == Boardpost && f.user_id == @user.id%>
    <div class="row">
      <div class="col s12">
        <div class="card grey lighten-2">
          <div class="card-content cyan-text text-darken-3">
                <span class="card-title">You've created a new Post</span>
                <span class="grey-text text-lighten-1"><h6> Posted at: <%= f.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h6></span>
                <div class="card grey lighten-4 center-align">
                <br><p><%= link_to "Category: #{@categories.find_by(id: f.boardcategory_id).name}", boardcategory_path(@categories.find_by(id: f.boardcategory_id)) %> <br> <%= link_to "Title: #{f.title}", boardpost_path(f)  %><br>
                  <br></p>
              </div>
            </div>
          </div>
        </div>
      </div>

    <% elsif f.class == Boardpost %>
    <div class="row">
      <div class="col s12">
        <div class="card grey lighten-2">
          <div class="card-content cyan-text text-darken-3">
                <span class="card-title"><strong><%= link_to "#{@users.find_by(id: f.user_id).username}", user_path(@users.find_by(id: f.user_id)) %></strong> created a new Post</span>
                <span class="grey-text text-lighten-1"><h6> Posted at: <%= f.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h6></span>
                <div class="card grey lighten-4 center-align">
                <br><p><%= link_to "Category: #{@categories.find_by(id: f.boardcategory_id).name}", boardcategory_path(@categories.find_by(id: f.boardcategory_id)) %> <br> <%= link_to "Title: #{f.title}", boardpost_path(f)  %><br>
                  <br></p>
              </div>
            </div>
          </div>
        </div>
      </div>

        <% elsif f.class == Connection && f.user_id == @user.id%>
        <div class="row">
          <div class="col s12">
            <div class="card grey lighten-2">
              <div class="card-content cyan-text text-darken-3">
                    <span class="card-title">You've connected to <strong><%=link_to "#{@user.find(f.connected_user_id).username}", user_path(@user.find(f.connected_user_id)) %></strong>now.</span>
                    <span class="grey-text text-lighten-1"><h6> Posted at: <%= f.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h6></span>
                  </div>
                </div>
              </div>
            </div>

        <% elsif f.class == Connection %>
        <div class="row">
          <div class="col s12">
            <div class="card grey lighten-2">
              <div class="card-content cyan-text text-darken-3">
                    <span class="card-title"><strong><%=link_to "#{@users.find_by(id: f.user_id).username}", user_path(@users.find_by(id: f.user_id))%></strong> connected with
                    <% if @user == @users.find_by(id: f.connected_user_id)%>
                    You</span>
                    <% else %>
                    <strong><%=link_to "#{@users.find_by(id: f.connected_user_id).username}", user_path(@users.find_by(id: f.connected_user_id))%></strong></span>

                    <% end %>
                    <span class="grey-text text-lighten-1"><h6> Posted at: <%= f.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h6></span>
                    <br>
                  </div>
                </div>
              </div>
            </div>

        <% elsif f.class == Useraudiofile %>
        <div class="row">
          <div class="col s12">
            <div class="card grey lighten-2">
              <div class="card-content cyan-text text-darken-3">
                    <span class="card-title"><strong><%=link_to "#{@users.find_by(id: f.user_id).username}", user_path(@users.find_by(id: f.user_id))%></strong> uploaded some music.</span>
                    <span class="grey-text text-lighten-1"><h6> Posted at: <%= f.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h6></span>
                    <br>
                  </div>
                </div>
              </div>
            </div>

      <% end %>

      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Find Musicians!</h1>

<br>
<div class="center-align">
  <div class="container">
    <div class="row">
      <div class="col s12 l12">
        <div class="card">
          <form action="/searches" method="get">
            <div class="input-field">
              <input id="search" type="search" name="keyword" required>
              <i class="material-icons">close</i>
            </div>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="center-align">
  <input type="submit" value="Search" class="btn valign"><br>
  <br>

<a class="waves-effect waves-light btn-small" href="#modal1">Advanced Search</a>
<div id="modal1" class="modal">
  <div class="modal-content">
  <%=render "/searches/advanced_form"%>
  </div>
</div>
</div>

<% if @locations %>
  <% @locations.each do |location| %>
    <%= location.title %><br />
    <%= location.user_id %><br />
    <%= link_to  location.title, user_path(location.user_id) %><br>
  <% end %>
<% end %>

<%@users.each do |u| %>
  <% if u.username %>

    <%=link_to "#{u.username}", user_path(u.id) %><br>
  <% elsif u.full_name%>
    <%= link_to "#{u.full_name}", user_path(u.id)%> %>
  <% end %>
  <% if u.genre %>
    <%="Playing styles: #{u.genre}" %><br><br>
  <% end %>


<% end %>

app/views/users/show.html.erb
<br>
<div class="pagewrapper">
      <div class="profile">
        <div class="row">
          <div class="col s12 l5 offset-s2">
            <div class="card-panel grey lighten-2 z-depth-5">
              <div class="center-align">
                <div class="row">
                  <div class="col s12">
                <%= image_tag @user.avatar.url(:thumb), :class => "circle responsive-img" %>
                <span class="cyan-text text-darken-3">
                  <h3><strong><%= @user.username %></strong></h3>
                  <%= @user.slogan %></span><br>
                  <br>
              </div>
            </div>
                </div>
                </div>
              </div>
            </div>
          </div>
  <div class="row">
    <div class="col s12 l5 offset-s2">
      <div class="card-panel cyan darken-3 z-depth-5">
        <div class="biocontent">
          <div class="row">
            <div class="col s12 l5 offset-s1">
              <div class="card small grey lighten-2 z-depth-5">
                <div class="card-content cyan-text text-darken-3">
                  <span class="card-title"><h4>
                      <i class="material-icons">info_outline</i>
              <strong>Info</strong></h4></span>
              <p>
                <span><h6><strong>Name: </strong><%= @user.full_name %></h6></span>
                <span><h6><strong>Location: </strong><%= @user.location %></h6></span>
                <span><h6><strong>Band Status: </strong><%= @user.band_status %></h6></span>
                <span><h6><strong>Genre: </strong><%= @user.genre %></h6></span>
                <span><h6><strong>Experience: </strong><%= @user.experience %></h6></span>
                <span><h6><strong>Instruments: </strong><%= @user.instruments %></h6></span>
              </p>
            </div>
          </div>
        </div>
        <div class="col s12 l5 offset-s1">
          <div class="card small grey lighten-2 z-depth-5">
            <div class="card-content cyan-text text-darken-3">
              <span class="card-title"><h4>
                <i class="material-icons">perm_identity</i>
                <strong>Bio</strong></h4></span>
                <p>
                  <%= @user.bio %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
          <div class="addmedia">
              <div class="row">
                <div class="col s12 l5 offset-s1">
                  <div class="card-panel grey lighten-2 z-depth-5">
                    <div class="card-content cyan-text text-darken-3">
                      <span class="card-title"><h4>
                        <i class="material-icons">settings_input_composite</i>
                        <strong>Connections</strong></h4></span>
                        <%= link_to "ALL", user_connections_path(@user) %>
                 <% @connections.limit(6).each do |connection|%>
                  <ul class="collection">
                    <li class="collection-item avatar">
                      <%= image_tag connection.connected_user.avatar.url(:large), :class => "circle"%>
                      <p><strong><%= link_to "#{connection.connected_user.username}", user_path(connection.connected_user) %></strong><br>
                      </p>
                    </li>
                  </ul>
                  <% end %>
                    </div>
                  </div>
                </div>

          <div class="col s12 l5 offset-s1">
            <div class="card-panel grey lighten-2 z-depth-5">
              <div class="card-content cyan-text text-darken-3">
                <span class="card-title"><h4>
                  <i class="material-icons">album</i>
                  <strong>Music</strong></h4></span>
                  <div class="container">
                  <% if current_user == @user %>
                    <a class="modal-trigger waves-effect waves-light btn" href="#modal1">Upload Your Music!</a>
                  <% end %>
                    <div id="modal1" class="modal">
                      <div class="modal-content">
                        <%=render "/useraudiofiles/new"%>
                      </div>
                    </div>
                  </div>
                </div>
                <br>
                <p>
                  <% @user.useraudiofiles.each do |file| %>
                  <%= audio_tag file.media_file_name unless file.media_file_name.blank? %>
                  <% end %>
                </div>
              </p>
            </div>
          </div>
        </div>
        <center>
        <div class="container">
          <div class="row">
            <div class="col s12 l6">
              <% if current_user && current_user.id == @user.id %>
              <%= link_to("edit profile", edit_user_path(@user), :class => "waves-effect waves-light btn" ) %>
            </div>
              <div class="col s12 m6 l6">
                <%= link_to("Change password", edit_user_registration_path, :class => "waves-effect waves-light btn") %>
              </div>
              <% else %>
              <%  if current_user.connected_users.include?(@user)%>
                <div class="col s12 l6">
              <%= button_to "Disconnect from #{@user.username}", delete_connection_path(@user), method: :delete, :class => "btn waves-effect waves-light" %>
              <% else %>
              <%= button_to "Connect with #{@user.username}", "/users/#{@user.id}/connections", method: "POST", :class => "btn waves-effect waves-light" %>
              <% end %>
              <% end %>
                    </div>
                  </div>
                </div>
              </center>
        <div class="row">
          <div class="col s12 l6">
        <% if current_user && current_user.id != @user.id%>
          <% if !current_user.has_convo?(@user) %>
            <%= button_to "Create Conversation", user_user_conversations_path(@user), method: "POST", :class => "waves-effect waves-light btn"  %>
          <% else %>
            <%= link_to "Message", conversation_path(current_user.find_convo(@user)), :class => "waves-effect waves-light btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
<% if current_user == @user %>
<center>
  <a class="waves-effect waves-light btn" href="#modal2">Messages</a>
</center>

  <!-- Modal Structure -->
  <div id="modal2" class="modal">
    <div class="modal-content">
      <h4>Messages</h4>
      <div> <div class="row">
       <div class="col s12 l12">
         <div class="card-panel grey lighten-2 z-depth-5">
           <div class="card-content cyan-text text-darken-3">
             <span class="card-title"><h4>
               <i class="material-icons">messagee</i>
               <strong>Messages</strong></h4></span>
               <%= link_to "ALL", conversations_path %>
                    <% @conversations.each do |convo|%>
                     <ul class="collection">
                       <li class="collection-item avatar">
                         <%= image_tag convo.other_user(@user).avatar.url(:large), :class => "circle"%>
                         <p><strong><%= link_to "#{convo.other_user(@user).username}", conversation_path(convo) %></strong><br>
                         </p>
                       </li>
                     </ul>
                     <% end %>
                   </div>
                  </div>
                 </div>
               </div>
               <% end %>
             </div>
             </div>
           </div>
<br>
<br>

        </div>
    </div>
  </div>
</div>

  <br><br><br>
  <% if current_user && current_user.id == @user.id %>
  <%= link_to("Update your location", new_location_path) %><br>
  <% end %>